<?php
declare (strict_types = 1);

namespace BusyPHP\command;

use BusyPHP\App;
use BusyPHP\contract\interfaces\PluginCommandInitialize;
use BusyPHP\helper\FileHelper;
use Exception;
use think\console\Command;
use think\console\Input;
use think\console\input\Option;
use think\console\Output;
use think\Container;
use think\exception\ClassNotFoundException;
use think\exception\FileException;
use ZipArchive;

/**
 * Composer安装指令
 * @author busy^life <busy.life@qq.com>
 * @copyright (c) 2015--2021 ShanXi Han Tuo Technology Co.,Ltd. All rights reserved.
 * @version $Id: 2020/6/6 下午9:49 下午 Install.php $
 * @property App $app
 */
class InstallCommand extends Command
{
    /**
     * @var array
     */
    protected $list;
    
    
    protected function configure()
    {
        // 指令配置
        $this->setName('bp:install')
            ->addOption('dev', 'd', Option::VALUE_OPTIONAL, 'composer.json path', null)
            ->setDescription('BusyPHP Framework composer install command');
    }
    
    
    protected function execute(Input $input, Output $output)
    {
        // 初始化
        if (!$this->init()) {
            return;
        }
        
        // 解压文件
        if (!$this->extract()) {
            return;
        }
        
        // 安装配置文件
        if (!$this->moveConfig()) {
            return;
        }
        
        // 初始化插件
        if (!$this->pluginInitialize()) {
            return;
        }
        
        $output->info("BusyPHP V{$this->app->getFrameworkVersion()} 初始化完成");
    }
    
    
    /**
     * 初始化
     * @return bool
     */
    protected function init()
    {
        $serviceFile = $this->app->getRootPath() . 'vendor' . DIRECTORY_SEPARATOR . 'busyphp_services.php';
        $services    = [];
        
        // 将BusyPHP框架支持的扩展 services 放进去
        $packages = $this->getPackages();
        foreach ($packages as $package) {
            foreach ($package['services'] ?? [] as $service) {
                $services[] = $service;
            }
        }
        
        $header  = '// This file is automatically generated at:' . date('Y-m-d H:i:s') . PHP_EOL . 'declare (strict_types = 1);' . PHP_EOL;
        $content = '<?php ' . PHP_EOL . $header . "return " . var_export($services, true) . ';';
        FileHelper::write($serviceFile, $content);
        
        return true;
    }
    
    
    /**
     * 解压文件
     * @return bool
     */
    protected function extract()
    {
        $packages = $this->getPackages();
        $extracts = [];
        foreach ($packages as $package) {
            foreach ($package['extract'] ?? [] as $source => $to) {
                $extracts[] = [
                    'name'   => $package['name'],
                    'source' => $source,
                    'to'     => $to
                ];
            }
        }
        
        foreach ($extracts as $r) {
            if (!$this->doExtract($r['name'] . DIRECTORY_SEPARATOR . $r['source'], $r['to'])) {
                return false;
            }
        }
        
        return true;
    }
    
    
    /**
     * 执行解压
     * @param string $source
     * @param string $toDir
     * @return bool
     */
    private function doExtract($source, $toDir)
    {
        $sourceFile = $this->app->getRootPath() . 'vendor/' . $source;
        $toDir      = trim($toDir, '/');
        $lockFile   = $toDir . DIRECTORY_SEPARATOR . md5(str_replace('\\', '/', $source)) . '.lock';
        if (is_file($lockFile)) {
            return true;
        }
        
        try {
            if (!class_exists('ZipArchive')) {
                throw new ClassNotFoundException('需要启用ZipArchive扩展才能继续安装');
            }
            
            $this->output->info("开始解压文件: {$source} 至 {$toDir}");
            $zip = new ZipArchive();
            $res = $zip->open($sourceFile);
            if (true !== $res) {
                throw new FileException("打开文件失败: {$source}");
            }
            
            if (!$res = $zip->extractTo($this->app->getRootPath() . $toDir)) {
                $zip->close();
                
                throw new FileException("解压文件失败: {$source}");
            }
            $zip->close();
            
            FileHelper::write($lockFile, "本文件为系统解压文件 {$source} 至 {$toDir} 后自动生成的防止重复解压锁，删除后重新执行Composer将会覆盖 {$toDir} 下的文件");
            
            $this->output->info("解压文件至: {$toDir} 成功!");
            
            return true;
        } catch (Exception $e) {
            $this->output->error($e->getMessage());
            
            return false;
        }
    }
    
    
    /**
     * 安装配置文件
     * @return bool
     */
    protected function moveConfig()
    {
        $packages  = $this->getPackages();
        $configDir = $this->app->getConfigPath() . DIRECTORY_SEPARATOR . 'extend' . DIRECTORY_SEPARATOR;
        if (!is_dir($configDir)) {
            if (!FileHelper::createDir($configDir)) {
                $this->output->error("配置文件目录不可写: {$configDir}");
                
                return false;
            }
        }
        
        foreach ($packages as $package) {
            $installPath = $this->app->getRootPath() . 'vendor/' . $package['name'] . DIRECTORY_SEPARATOR;
            foreach ($package['config'] ?? [] as $name => $file) {
                $target = $configDir . $name . '.php';
                $source = $installPath . $file;
                
                if (is_file($target)) {
                    $this->output->warning("配置文件 {$target} 已存在!");
                    continue;
                }
                
                if (!is_file($source)) {
                    $this->output->error("配置文件 {$source} 不存在!");
                    
                    return false;
                }
                
                if (!copy($source, $target)) {
                    $this->output->error("安装配置文件 {$source} 至 {$target} 失败!");
                    
                    return false;
                }
                
                $this->output->info("安装配置文件 {$source} 至 {$target} 成功.");
            }
        }
        
        return true;
    }
    
    
    /**
     * 初始化插件
     */
    protected function pluginInitialize()
    {
        $packages    = $this->getPackages();
        $initializes = [];
        foreach ($packages as $package) {
            foreach ($package['initializes'] ?? [] as $initialize) {
                $initializes[] = $initialize;
            }
        }
        
        foreach ($initializes as $initialize) {
            if (!$initialize || !class_exists($initialize)) {
                continue;
            }
            
            $obj = Container::getInstance()->make($initialize, [], true);
            if (!$obj instanceof PluginCommandInitialize) {
                continue;
            }
            
            try {
                $obj->initialize($this->output);
            } catch (Exception $e) {
                return false;
            }
        }
        
        return true;
    }
    
    
    /**
     * 获取Composer项目列表
     * @return array
     */
    private function getPackages()
    {
        if (isset($this->list)) {
            return $this->list;
        }
        
        $packages = [];
        if (is_file($path = $this->app->getRootPath() . 'vendor/composer/installed.json')) {
            $packages = json_decode(@file_get_contents($path), true);
        }
        
        // Compatibility with Composer 2.0
        if (isset($packages['packages'])) {
            $packages = $packages['packages'];
        }
        
        $devComposerFile = $this->input->getOption('dev') ?: '';
        if ($devComposerFile) {
            if (!is_file($devComposerFile)) {
                $devComposerFile = $this->app->getRootPath() . $devComposerFile;
            }
            
            $packages[] = json_decode(@file_get_contents($devComposerFile), true);
        }
        
        $list = [];
        foreach ($packages as $package) {
            if (!isset($package['extra']['busyphp'])) {
                continue;
            }
            
            $package['extra']['busyphp']['name'] = $package['name'];
            $list[]                              = $package['extra']['busyphp'];
        }
        
        $this->list = $list;
        
        return $this->list;
    }
}
